import { prisma } from "../lib/prisma.js";
import { syncAgentDefinitions } from "../data/agents.js";
import { syncProviderProfiles } from "../data/providers.js";

async function seed() {
  await syncProviderProfiles();
  await syncAgentDefinitions();

  await prisma.taskRequest.create({
    data: {
      agentId: "athena",
      title: "Seeded operator walkthrough",
      description: "A seeded request used to demonstrate the operator workflow.",
      contextNote: "Generated by the local seed script.",
      status: "completed",
      runs: {
        create: {
          status: "completed",
          latestMessage: "Seeded run completed.",
          resultSummary: "Generated a seeded operator walkthrough result.",
          resultPayload: {
            summary: "Seed data is active.",
            confidence: "high",
            artifacts: ["catalog", "queue", "review"]
          },
          completedAt: new Date(),
          events: {
            create: [
              {
                eventType: "submitted",
                message: "Seeded task request submitted."
              },
              {
                eventType: "status_changed",
                message: "Seeded run marked completed."
              }
            ]
          },
          reviewDecision: {
            create: {
              verdict: "approved",
              notes: "Seeded review decision."
            }
          }
        }
      }
    }
  });
}

seed()
  .then(async () => {
    await prisma.$disconnect();
    console.log("Agora seed complete.");
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
